name: R Testing

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]

env:
  IMAGE_NAME: ghcr.io/dennislarsson/r_image:set-up-ci-workflow-a4a19c3@sha256:281607d993dcba52fd49582ac7054cd949bccf3ec9391dd0fa8eaa4a8d0725fc

jobs:
  test-r:
    runs-on: ubuntu-22.04
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }} 

      - name: Pull the Docker image
        run: docker pull ${{ env.IMAGE_NAME }}
  
      - name: Checkout repository
        uses: actions/checkout@v4.1.6

      - name: Run R script in container and copy output files
        run: |
          # Run the container in the background and get the container ID
          container_id=$(docker run -d \
            -v $(pwd)/test_files:/test_files \
            -v $(pwd)/PCA2.2.R:/PCA2.2.R \
            ${{ env.IMAGE_NAME }} \
            Rscript PCA2.2.R)

          # Copy the output files
          docker cp $container_id:/output/ /output/

          # Stop and remove the container
          docker stop $container_id
          docker rm $container_id

      - name: Check the content of output folder
        run: ls /output/

      - name: Compare PDF outputs
        run: |
          # Assuming generated PDFs are in the same directory as the script
          diff expected_files/expected_PCA.pdf /output/PCA_spicatum_group.pdf

      - name: Compare PNG outputs
        run: |
          # Assuming generated PNGs are in the same directory as the script
          diff expected_files/expected_PCA_PC1_2.png /output/PCA_spicatum_group_PC1_2.png
          diff expected_files/expected_PCA_PC1_3.png /output/PCA_spicatum_group_PC1_3.png