name: R Testing

on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]

jobs:
  test-r:
    runs-on: ubuntu-22.04
    container: ghcr.io/dennislarsson/r_image:set-up-ci-workflow-a4a19c3@sha256:281607d993dcba52fd49582ac7054cd949bccf3ec9391dd0fa8eaa4a8d0725fc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6

      - name: Run R script
        run: Rscript PCA2.2.R

      - name: Compare PDF outputs
        run: |
          # Assuming generated PDFs are in the same directory as the script
          diff expected_files/expected_PCA.pdf PCA_spicatum_group.pdf

      - name: Compare PNG outputs
        run: |
          # Assuming generated PNGs are in the same directory as the script
          diff expected_files/expected_PCA_PC1_2.png PCA_spicatum_group_PC1_2.png
          diff expected_files/expected_PCA_PC1_3.png PCA_spicatum_group_PC1_3.png